### ISSUE TITLE
What about samPackage()?

### ISSUE THREAD

**Issue by atifrasheed79** [jenkinsci/aws-sam-plugin#1]
Hi Jenkins team,

In the usage section, you only mentioned about samDeploy() function which I understand can be used from Jenkinsfile (script) now. But what about samPackage()? Do we still have to use Shell for packaging? 

Thanks.
--
Atif

**Comment by atifrasheed79** [comment]
Just to add, the "build" step GUI in plug-in documentation only shows in a Freestyle Project! What about Pipeline or a Multi-branch Pipeline? How we are going to build package in a scripted pipeline? Please advise.

Thanks.

**Comment by chukkalapradeep** [comment]
> e still have to use Shell for packaging?

Hi Atif,

I find that the samDeploy does both Packaging and deployment. So no need to call the Packaging separately.

Regards,
pradeep

**Comment by hoffa** [comment]
Indeed packaging happens as part of the deployment:

https://github.com/jenkinsci/aws-sam-plugin/blob/a0005657b325a5e236d120aed5cd37e03061d9f4/src/main/java/com/amazonaws/jenkins/plugins/sam/DeployBuildStep.java#L77-L78
