### ISSUE TITLE
samDeploy command only does 'sam package' and 'sam deploy' but not 'sam build'

### ISSUE THREAD

**Issue by HariDurga** [jenkinsci/aws-sam-plugin#23]
Is there any plugin in Jenkins to do sam build? I feel the whole point of using the plugin is to avoid installing AWS SAM CLI on Jenkins. But since the current plugin is not supporting sam build and looks like I need to install the AWS SAM CLI on Jenkins IAM.
Correct me if I am missing something here.

**Comment by mew1033** [comment]
I'm also wondering about a sam build pipeline step. Did you ever find anything?

You could do the build in a docker container and use one of the AWS provided sam build images: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-image-repositories.html

**Comment by HariDurga** [comment]
Hi,

I haven’t find anything. But it would be great if there is plug-in to build and deploy. Deploy works ok for me but is not building. 

There is one more approach as to install AWS Sam in the Jenkins IAM.

But I can try using a container as well.

Hari

**Comment by hoffa** [comment]
Unfortunately there's no way to support `sam build` through the plugin without calling it directly (which would somewhat defeat the plugin's purpose, as it would require installing SAM CLI first), or without essentially reimplementing `sam build`. As @mew1033 called out, you can use the SAM build images to use the full set of SAM CLI features in Jenkins.
