### ISSUE TITLE
WaiterUnrecoverableException when deploy a Step Function use SAM

### ISSUE THREAD

**Issue by mjfuInrix** [jenkinsci/aws-sam-plugin#26]
### Jenkins and plugins versions report

Result
Jenkins: 2.303.1
OS: Linux - 4.14.231-173.360.amzn2.x86_64
---
Office-365-Connector:4.15.2
ace-editor:1.1
analysis-model-api:10.8.1
ant:1.13
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
artifactory:3.15.1
atlassian-jira-software-cloud:1.4.5
authentication-tokens:1.4
aws-credentials:1.33
aws-java-sdk:1.12.131-302.vbef9650c6521
aws-java-sdk-cloudformation:1.12.131-302.vbef9650c6521
aws-java-sdk-codebuild:1.12.131-302.vbef9650c6521
aws-java-sdk-ec2:1.12.131-302.vbef9650c6521
aws-java-sdk-ecr:1.12.131-302.vbef9650c6521
aws-java-sdk-ecs:1.12.131-302.vbef9650c6521
aws-java-sdk-elasticbeanstalk:1.12.131-302.vbef9650c6521
aws-java-sdk-iam:1.12.131-302.vbef9650c6521
aws-java-sdk-logs:1.12.131-302.vbef9650c6521
aws-java-sdk-minimal:1.12.131-302.vbef9650c6521
aws-java-sdk-ssm:1.12.131-302.vbef9650c6521
aws-sam:1.2.5
blueocean:1.25.2
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
build-environment:1.7
build-name-setter:2.2.0
build-timeout:1.20
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:746.v350d2781c184
cloudbees-folder:6.17
cobertura:1.17
code-coverage-api:2.0.4
codedeploy:1.23
command-launcher:1.6
conditional-buildstep:1.4.1
config-file-provider:3.8.2
copyartifact:1.46.2
credentials:2.6.1
credentials-binding:1.27.1
data-tables-api:1.11.3-6
display-url-api:2.3.5
docker-commons:1.18
docker-java-api:3.1.5.2
docker-plugin:1.2.6
docker-workflow:1.27
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
email-ext:2.86
favorite:2.3.3
font-awesome-api:5.15.4-5
forensics-api:1.7.0
git:4.10.1
git-client:3.11.0
git-parameter:0.9.14
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.4
gradle:1.38
groovy:2.4
h2-api:1.4.199
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.28
ivy:2.1
jackson2-api:2.13.1-246.va8a9f3eaf46a
javadoc:1.6
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.2
jira:3.6
jjwt-api:0.11.2-9.c8b45b8bb173
jobConfigHistory:2.31-rc1098.b666422863b2
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes-cli:1.10.3
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials:0.9.0
ldap:2.7
lockable-resources:2.13
mailer:408.vd726a_1130320
matrix-auth:3.0
matrix-project:1.20
maven-plugin:3.16
momentjs:1.1.1
nodejs:1.5.0
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.6.1
parameterized-trigger:2.43
pipeline-aws:1.43
pipeline-build-step:2.16
pipeline-github-lib:1.0
pipeline-graph-analysis:1.11
pipeline-input-step:427.va6441fa17010
pipeline-maven:3.10.0
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.21
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
plain-credentials:1.7
plugin-util-api:2.12.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
prism-api:1.25.0-1
pubsub-light:1.16
python:1.3
rebuild:1.33
resource-disposer:0.17
role-strategy:3.2.0
run-condition:1.5
scm-api:595.vd5a_df5eb_0e39
script-security:1131.v8b_b_5eda_c328e
semantic-versioning-plugin:1.13
snakeyaml-api:1.29.1
sse-gateway:1.24
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:308.v852b473a2b8c
timestamper:1.16
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
warnings-ng:9.10.3
workflow-aggregator:2.6
workflow-api:1108.v57edf648f5d4
workflow-basic-steps:2.24
workflow-cps:2656.vf7a_e7b_75a_457
workflow-cps-global-lib:561.va_ce0de3c2d69
workflow-durable-task-step:2.40
workflow-job:1145.v7f2433caa07f
workflow-multibranch:707.v71c3f0a_6ccdb_
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
ws-cleanup:0.40

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: Linux - 4.14.231-173.360.amzn2.x86_64

### Reproduction steps

I was trying to deploy a step function (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html) with lambdas.  The step function was defined in a separate json file under the same folder. 

It works fine when I use the sam cli with the following commands but failed when using the sam jenkins plugin. 

```
sam build
sam deploy --guided
```

Here is the example of template.yaml

```
  DatasetCleanupPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: StepFunction-Test
      DefinitionUri: test/step_function.asl.json
      DefinitionSubstitutions:
        ReportDeletionLambdaArn: !GetAtt LambdaFunc.Arn

  LambdaFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test/functions
      Handler: lambda.lambda_delete_reports
      Timeout: 900
```

Checking S3 bucket, only lambda functions got upalao

### Expected Results

A Step Function and lambda function should be deployed via CloudFormation

### Actual Results

.....(some pip installs)
Successfully installed certifi-2022.5.18.1 charset-normalizer-2.0.12 idna-3.3 requests-2.27.1 urllib3-1.26.9

Validating template...
Uploading: cddb8a5df704b2ef1ee15fe90a4a4c5e
Uploading: 8c67376d707350ea521d95067d11d4fb
Successfully packaged artifacts.
Output template: template-19.yaml
Creating ChangeSet...
ERROR: Build step failed with exception
com.amazonaws.waiters.WaiterUnrecoverableException: Resource never entered the desired state as it failed.
	at com.amazonaws.waiters.WaiterExecution.pollResource(WaiterExecution.java:78)
	at com.amazonaws.waiters.WaiterImpl.run(WaiterImpl.java:88)
	at com.amazonaws.jenkins.plugins.sam.service.CloudFormationService.waitForChangeSet(CloudFormationService.java:105)
Caused: com.amazonaws.jenkins.plugins.sam.model.SamPluginException: ChangeSet cannot be created
	at com.amazonaws.jenkins.plugins.sam.service.CloudFormationService.waitForChangeSet(CloudFormationService.java:111)
	at com.amazonaws.jenkins.plugins.sam.service.CloudFormationService.createChangeSet(CloudFormationService.java:66)
	at com.amazonaws.jenkins.plugins.sam.DeployBuildStep.createChangeSet(DeployBuildStep.java:113)
	at com.amazonaws.jenkins.plugins.sam.DeployBuildStep.perform(DeployBuildStep.java:84)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:21)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:808)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:516)
	at hudson.model.Run.execute(Run.java:1889)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:100)
	at hudson.model.Executor.run(Executor.java:433)
Build step 'AWS SAM deploy application' marked build as failure

**Comment by SimonCMoore** [comment]
We recommend switching to using SAM CLI with Jenkins rather than this plugin to support newer features, to get started see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-generating-example-ci-cd-others.html
and https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/deploying-using-jenkins.html
